<a href="https://colab.research.google.com/github/vikrampal12345/Machine_learning/blob/main/7_OneHotEncolding_Feature_scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# OneHotEncoding
# Dummy Variable Trap
# OHE using  most Frequent variables
# Example

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("cars.csv")
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [ ]:
df['brand'].value_counts()     # count the numbers of car of the brand

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [ ]:
df['brand'].nunique()   # it give the count of the unique car brands

32

In [ ]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [ ]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

# 1. OneHotEncoding using Pandas

In [ ]:
pd.get_dummies(df, columns = ['fuel', 'owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

# n-1 Encoding ( remove the first column so the missilinity not arise(means every input column are mathmatically independent))

In [ ]:
# we cannot use the pandas onehot encoding in the machine learning
# because it not remember the columns.
# so everytime it give different value

pd.get_dummies(df, columns = ['fuel', 'owner'], drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# 3. OneHotEncoding using sklearn

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:4], df.iloc[:,-1], test_size=0.2, random_state=0)

In [ ]:
df.iloc[:,0:4]

        brand  km_driven    fuel                 owner
0      Maruti     145500  Diesel           First Owner
1       Skoda     120000  Diesel          Second Owner
2       Honda     140000  Petrol           Third Owner
3     Hyundai     127000  Diesel           First Owner
4      Maruti     120000  Petrol           First Owner
...       ...        ...     ...                   ...
8123  Hyundai     110000  Petrol           First Owner
8124  Hyundai     119000  Diesel  Fourth & Above Owner
8125   Maruti     120000  Diesel           First Owner
8126     Tata      25000  Diesel           First Owner
8127     Tata      25000  Diesel           First Owner

[8128 rows x 4 columns]

In [ ]:
df.iloc[:,-1]

0       450000
1       370000
2       158000
3       225000
4       130000
         ...
8123    320000
8124    135000
8125    382000
8126    290000
8127    290000
Name: selling_price, Length: 8128, dtype: int64

In [ ]:
from sklearn.preprocessing import OneHotEncoder

# sparse = False - it convert the data into numpy array
# drop = first - remove the first column
# dtype = np.int32 - float data convert into the integer data

ohe =  OneHotEncoder(drop='first', dtype=np.int32)

X_train_new = ohe.fit_transform(X_train[['fuel', 'owner']])

X_test_new = ohe.transform(X_test[['fuel', 'owner']])

X_train_new.shape

(6502, 7)

In [ ]:
X_train_new.toarray()

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], dtype=int32)

In [ ]:
from scipy.sparse import hstack
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

# 4. OneHotEncoding with Top Categories

In [ ]:
counts = df["brand"].value_counts() # count the value of the brand

In [ ]:
df['brand'].nunique()
threshold = 100

In [ ]:
relp = counts[counts <= threshold].index  # we extarct the brand which is less than 100 cars

In [ ]:
pd.get_dummies(df['brand'].replace(relp, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
4519,False,False,True,False,False,False,False,False,False,False,False,False,False
6739,False,False,False,False,False,True,False,False,False,False,False,False,False
7260,False,False,True,False,False,False,False,False,False,False,False,False,False
5005,False,False,False,False,False,False,False,False,False,False,False,False,True
5610,False,False,False,False,False,False,True,False,False,False,False,False,False