<a href="https://colab.research.google.com/github/vikrampal12345/Machine_learning/blob/main/12_Missing_Everytype_DataHandling/2_Handle_Date_Time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Handle Date and Time columns

In [13]:
import pandas as pd
import numpy as np

date = pd.read_csv("orders.csv")
time = pd.read_csv("messages.csv")

In [14]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [15]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [16]:
date.info()               # date is an object so first convert in to datetimeobj

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

## working with date

In [17]:
# Converting to datetime datatype

date['date'] = pd.to_datetime(date['date'])

In [18]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

1. Extract year

In [19]:
date['date_year'] = date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

2. Extract the month

In [20]:
date['date_month_no'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

3. Extract the day

In [21]:
date['date_day'] = date['date'].dt.day
date.head()

        date  product_id  city_id  orders  date_year  date_month_no  date_day
0 2019-12-10        5628       25       3       2019             12        10
1 2018-08-15        3646       14     157       2018              8        15
2 2018-10-23        1859       25       1       2018             10        23
3 2019-08-17        7292       25       1       2019              8        17
4 2019-01-06        4344       25       3       2019              1         6

4. Extract the month name

In [22]:
date['date_month_name'] = date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day,date_month_name
0,2019-12-10,5628,25,3,2019,12,10,December
1,2018-08-15,3646,14,157,2018,8,15,August
2,2018-10-23,1859,25,1,2018,10,23,October
3,2019-08-17,7292,25,1,2019,8,17,August
4,2019-01-06,4344,25,3,2019,1,6,January

5. day of week

In [24]:
date['date_dow'] = date['date'].dt.dayofweek
date.head(2)

,date,product_id,city_id,orders,date_year,date_month_no,date_day,date_month_name,date_dow
0,2019-12-10,5628,25,3,2019,12,10,December,1
1,2018-08-15,3646,14,157,2018,8,15,August,2

6. Extract the day name

In [25]:
date['date_day_week_name'] = date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day,date_month_name,date_dow,date_day_week_name
0,2019-12-10,5628,25,3,2019,12,10,December,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,15,August,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,23,October,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,17,August,5,Saturday
4,2019-01-06,4344,25,3,2019,1,6,January,6,Sunday

7. Extract the weekend

In [26]:
date['date_weekend'] = np.where(date['date_day_week_name'].isin(['Sunday', 'Saturday']),1,0)
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_month_name,date_dow,date_day_week_name,date_weekend
0,2019-12-10,2019,12,10,December,1,Tuesday,0
1,2018-08-15,2018,8,15,August,2,Wednesday,0
2,2018-10-23,2018,10,23,October,1,Tuesday,0
3,2019-08-17,2019,8,17,August,5,Saturday,1
4,2019-01-06,2019,1,6,January,6,Sunday,1

8. Extract week of the year

In [29]:
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_month_name,date_dow,date_day_week_name,date_weekend,date_week
0,2019-12-10,2019,12,10,December,1,Tuesday,0,50
1,2018-08-15,2018,8,15,August,2,Wednesday,0,33
2,2018-10-23,2018,10,23,October,1,Tuesday,0,43
3,2019-08-17,2019,8,17,August,5,Saturday,1,33
4,2019-01-06,2019,1,6,January,6,Sunday,1,1

9. Extract Quarter

In [30]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_month_name,date_dow,date_day_week_name,date_weekend,date_week,quarter
0,2019-12-10,2019,12,10,December,1,Tuesday,0,50,4
1,2018-08-15,2018,8,15,August,2,Wednesday,0,33,3
2,2018-10-23,2018,10,23,October,1,Tuesday,0,43,4
3,2019-08-17,2019,8,17,August,5,Saturday,1,33,3
4,2019-01-06,2019,1,6,January,6,Sunday,1,1,1

10. Extract the semester

In [31]:
date['semester'] = np.where(date['quarter'].isin([1,2]),1,2)
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_month_name,date_dow,date_day_week_name,date_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,10,December,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,15,August,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,23,October,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,17,August,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,6,January,6,Sunday,1,1,1,1

11. Extract Time elapsed between dates

In [32]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 6, 21, 8, 58, 4, 493211)

In [33]:
today - date['date']

0     2385 days 08:58:04.493211
1     2867 days 08:58:04.493211
2     2798 days 08:58:04.493211
3     2500 days 08:58:04.493211
4     2723 days 08:58:04.493211
                 ...
995   2813 days 08:58:04.493211
996   2754 days 08:58:04.493211
997   2602 days 08:58:04.493211
998   2667 days 08:58:04.493211
999   2441 days 08:58:04.493211
Name: date, Length: 1000, dtype: timedelta64[ns]

In [34]:
# day
(today - date['date']).dt.days

0      2385
1      2867
2      2798
3      2500
4      2723
       ...
995    2813
996    2754
997    2602
998    2667
999    2441
Name: date, Length: 1000, dtype: int64

In [38]:
# months passed

import pandas as pd

today = pd.Timestamp.today()

date['date'] = pd.to_datetime(date['date'])

date['months_passed'] = (
    (today.year - date['date'].dt.year) * 12
    + (today.month - date['date'].dt.month)
)
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day,date_month_name,date_dow,date_day_week_name,date_weekend,date_week,quarter,semester,months_passed
0,2019-12-10,5628,25,3,2019,12,10,December,1,Tuesday,0,50,4,2,78
1,2018-08-15,3646,14,157,2018,8,15,August,2,Wednesday,0,33,3,2,94
2,2018-10-23,1859,25,1,2018,10,23,October,1,Tuesday,0,43,4,2,92
3,2019-08-17,7292,25,1,2019,8,17,August,5,Saturday,1,33,3,2,82
4,2019-01-06,4344,25,3,2019,1,6,January,6,Sunday,1,1,1,1,89

 # Extract the Time

In [39]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [41]:
# converting to datetime datatype

time['date'] = pd.to_datetime(time['date'])
time.head()

                 date                                                msg
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4 2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

Extract hour, min, sec

In [42]:
time['hours'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hours,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

Extract Time part

In [43]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hours,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

Time difference

In [44]:
today - time['date']

0     4571 days 08:13:12.157825
1     4435 days 09:23:12.157825
2     4921 days 08:42:12.157825
3     4223 days 08:32:12.157825
4     4620 days 09:52:12.157825
                 ...
995   5210 days 08:13:12.157825
996   4531 days 09:49:12.157825
997   4996 days 09:26:12.157825
998   5112 days 09:29:12.157825
999   4384 days 09:38:12.157825
Name: date, Length: 1000, dtype: timedelta64[ns]

In [45]:
# in seconds

(today - time['date']) / np.timedelta64(1,'s')

0      3.949640e+08
1      3.832178e+08
2      4.252057e+08
3      3.648979e+08
4      3.992035e+08
           ...
995    4.501736e+08
996    3.915138e+08
997    4.316884e+08
998    4.417110e+08
999    3.788123e+08
Name: date, Length: 1000, dtype: float64

In [46]:
(today - time['date']) / np.timedelta64(1,'m')

0      6.582733e+06
1      6.386963e+06
2      7.086762e+06
3      6.081632e+06
4      6.653392e+06
           ...
995    7.502893e+06
996    6.525229e+06
997    7.194806e+06
998    7.361849e+06
999    6.313538e+06
Name: date, Length: 1000, dtype: float64

In [47]:
(today - time['date']) / np.timedelta64(1,'h')

0      109712.220044
1      106449.386711
2      118112.703377
3      101360.536711
4      110889.870044
           ...
995    125048.220044
996    108753.820044
997    119913.436711
998    122697.486711
999    105225.636711
Name: date, Length: 1000, dtype: float64