<a href="https://colab.research.google.com/github/vikrampal12345/Machine_learning/blob/main/14_Feature_Construction_splitting/Feature_contruction_splitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Feature Construction

In [43]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [44]:
dff = sns.load_dataset('titanic')
df = dff.iloc[:,[0,1,3,4,5]]

In [45]:
df.head()

   survived  pclass   age  sibsp  parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [46]:
df.dropna(inplace=True)

/tmp/ipykernel_1890/1379821321.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [47]:
x = df.drop('survived', axis=1)
y = df.iloc[:,0]

In [48]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

In [49]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((571, 4), (143, 4), (571,), (143,))

In [50]:
np.mean(cross_val_score(LogisticRegression(), x, y, scoring='accuracy', cv=20))

np.float64(0.6933333333333332)

# Applying Feature Construction

In [51]:
x["Family_size"] = x['sibsp'] + x['parch'] + 1  # passagner also consider

In [52]:
x

     pclass   age  sibsp  parch  Family_size
0         3  22.0      1      0            2
1         1  38.0      1      0            2
2         3  26.0      0      0            1
3         1  35.0      1      0            2
4         3  35.0      0      0            1
..      ...   ...    ...    ...          ...
885       3  39.0      0      5            6
886       2  27.0      0      0            1
887       1  19.0      0      0            1
889       1  26.0      0      0            1
890       3  32.0      0      0            1

[714 rows x 5 columns]

In [53]:
def myfunc(num):
  if num == 1:
    return 0
  elif num > 1 and num <= 4:
    return 1
  else:
    return 2

In [54]:
x['Family_type'] = x['Family_size'].apply(myfunc)

In [55]:
x

     pclass   age  sibsp  parch  Family_size  Family_type
0         3  22.0      1      0            2            1
1         1  38.0      1      0            2            1
2         3  26.0      0      0            1            0
3         1  35.0      1      0            2            1
4         3  35.0      0      0            1            0
..      ...   ...    ...    ...          ...          ...
885       3  39.0      0      5            6            2
886       2  27.0      0      0            1            0
887       1  19.0      0      0            1            0
889       1  26.0      0      0            1            0
890       3  32.0      0      0            1            0

[714 rows x 6 columns]

In [56]:
x = x.iloc[:,[0,1,5]]
x

     pclass   age  Family_type
0         3  22.0            1
1         1  38.0            1
2         3  26.0            0
3         1  35.0            1
4         3  35.0            0
..      ...   ...          ...
885       3  39.0            2
886       2  27.0            0
887       1  19.0            0
889       1  26.0            0
890       3  32.0            0

[714 rows x 3 columns]

In [57]:
np.mean(cross_val_score(LogisticRegression(), x, y, scoring='accuracy', cv=20))

np.float64(0.7003174603174602)

# Feature Splitting

In [58]:
var = pd.read_csv('/content/Tatanic_dataset.csv')
var.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [59]:
var['Title'] = var['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

In [60]:
var

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Rev
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Miss
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Miss
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Mr
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Mr

In [62]:
var.groupby('Title')['Survived'].mean().sort_values(ascending=False)

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64

In [64]:
var['Is_married'] = 0
var['Is_married'].loc[var['Title'] == 'Mrs'] = 1

/tmp/ipykernel_1890/1842983067.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  var['Is_married'].loc[var['Title'] == 'Mrs'] = 1
/tmp/ipykernel_1890/1842983067.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  var['Is_married'].loc[var['Title'] == 'Mrs'] = 1

In [65]:
 var['Is_married']

0      0
1      1
2      0
3      1
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: Is_married, Length: 891, dtype: int64